version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: philippzagar/hackatum-server:latest
    container_name: hackatum-server
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: api.hackatum.zagar.dev
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api.hackatum.zagar.dev
      LETSENCRYPT_EMAIL: p@zagar.dev
    networks:
      - hackatum-network

  mongo:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - hackatum-network

  client:
    image: philippzagar/hackatum-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: hackatum-client
    restart: unless-stopped
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: hackatum.zagar.dev
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: hackatum.zagar.dev
      LETSENCRYPT_EMAIL: p@zagar.dev
    networks:
      - hackatum-network

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENABLE_IPV6: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - server
      - client
    networks:
      - hackatum-network

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=p@zagar.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy:rw
    depends_on:
      - nginx-proxy
    networks:
      - hackatum-network

networks:
  hackatum-network:
    driver: bridge

volumes:
  data-volume:
