name: build-push-deploy

on:
  push:
    branches:
      - "main"
      - "develop"

env:
  IMAGE_NAME_CLIENT: philippzagar/hackatum-client
  IMAGE_NAME_SERVER: philippzagar/hackatum-server

jobs:
  build-push-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v3
        with:
          context: ./client
          file: ./client/Dockerfile
          tags: ${{ env.IMAGE_NAME_CLIENT }}
          push: true
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME_CLIENT }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME_CLIENT }}:buildcache,mode=max

  build-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile
          tags: ${{ env.IMAGE_NAME_SERVER }}
          push: true
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME_SERVER }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME_SERVER }}:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [build-push-client, build-push-server]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd hackatum
            docker compose down
            docker compose pull
            docker compose up -d
